### ISSUE TITLE
Error when trying to get PST embedding

### ISSUE THREAD

**Issue by AlyciaBHZ** [YuchiQiu/TopFit#1]
I am trying to get the PST embedding, however when I execute the following code:

```
dataset=YAP1_HUMAN_Fields2012-singles-linear 
a=0 
b=319
python3 src/PST_embedding.py $dataset $a $b
```

I got this:
```
Traceback (most recent call last):
  File "/TopFit/src/PST_embedding.py", line 97, in <module>
    runPST.main(feature_list,PDBid, Chain, mutations, num_sites, pH, ['WT','MT'],
  File "/TopFit/src/PST/runPST.py", line 71, in main
    pro_wt=pro_complex(PDBid, Chain, mutations,'WT')
  File "/TopFit/src/PST/PST_features.py", line 53, in __init__
    atoms_m_m,atoms_m_o = loadMutantPDB(PDBfile,muteChain,resID)
  File "/TopFit/src/PST/PST_features.py", line 128, in loadMutantPDB
    fp = open(PDBfile)
FileNotFoundError: [Errno 2] No such file or directory: '4rex_WT_A173.pdb'
```

This also keeps happening in my customized dataset, and it seems like asking for a specific mutated PDB file, how should I deal with this, thanks!

**Comment by YuchiQiu** [comment]
The code should generate the mutated PDB file. You need to install VMD and Jackal according to the instructions. If so, can you further check if you run code `get_structure` at Line 70 in scr/PST/runPST.py successfully?

**Comment by AlyciaBHZ** [comment]
Hi, thank you for your quick response, I think the problem lies in `src/PST/PST_structure.py line 69:  os.system('./scap -ini 20 -min 4 '+filename+'_WT.pdb tmp_scap.list')`
![image](https://github.com/YuchiQiu/TopFit/assets/50111876/2337c82b-0b45-44b1-9dce-db29e63701bb)
where gives the error:
![image](https://github.com/YuchiQiu/TopFit/assets/50111876/5e2ce3fe-c971-4e13-8a75-71a8ca181d94)
I tried `chmod +x scap` but this did not help, how can I possibly fix this, thanks!

**Comment by YuchiQiu** [comment]
You need to give permission to the directory to execute the program.
